mode_rules = {
        "C":{
            "Ionian": {"Db": "D", "Eb": "E", "F#": "F", "Gb": "G", "Ab": "A", "Bb": "B"},
            "Dorian": {"Db": "D", "E": "Eb", "F#": "F", "Gb": "G", "Ab": "A", "B": "Bb"},
            "Phrygian": {"D": "Db", "E": "Eb", "F#": "F", "Gb": "G", "A": "Ab", "B": "Bb"},
            "Lydian": {"Db": "D", "Eb": "E", "F": "F#", "Gb": "G", "Ab": "A", "Bb": "B"},
            "Mixolydian": {"Db": "D", "Eb": "E", "F#": "F", "Gb": "G", "Ab": "A", "B": "Bb"},
            "Aeolian": {"Db": "D", "E": "Eb", "F#": "F", "Gb": "G", "A": "Ab", "B": "Bb"},
            "Locrian": {"D": "Db", "E": "Eb", "F#": "F", "G": "Gb", "A": "Ab", "B": "Bb"},
        },
        "C#":{
            "Ionian": {"D": "D#", "E": "E#", "F##": "F#", "G": "G#", "A": "A#", "B": "B#"},
            "Dorian": {"D": "D#", "E#": "E", "F##": "F#", "G": "G#", "A": "A#", "B#": "B"},
            "Phrygian": {"D#": "D", "E#": "E", "F##": "F#", "G": "G#", "A#": "A", "B#": "B"},
            "Lydian": {"D": "D#", "E": "E#", "F#": "F##", "G": "G#", "A": "A#", "B": "B#"},
            "Mixolydian": {"D": "D#", "E": "E#", "F##": "F#", "G": "G#", "A": "A#", "B#": "B"},
            "Aeolian": {"D": "D#", "E#": "E", "F##": "F#", "G": "G#", "A#": "A", "B#": "B"},
            "Locrian": {"D#": "D", "E#": "E", "F##": "F#", "G#": "G", "A#": "A", "B#": "B"},
        },
        "Db":{
            "Ionian": {"Ebb": "Eb", "Fb": "F", "G#": "G", "Ab": "A", "Bb": "B", "Cb": "C"},
            "Dorian": {"Ebb": "Eb", "F": "Fb", "G#": "G", "Ab": "A", "Bb": "B", "C": "Cb"},
            "Phrygian": {"Eb": "Ebb", "F": "Fb", "G#": "G", "Ab": "A", "B": "Bb", "C": "Cb"},
            "Lydian": {"Ebb": "Eb", "Fb": "F", "G": "G#", "Ab": "A", "Bb": "B", "Cb": "C"},
            "Mixolydian": {"Ebb": "Eb", "Fb": "F", "G#": "G", "Ab": "A", "Bb": "B", "C": "Cb"},
            "Aeolian": {"Ebb": "Eb", "F": "Fb", "G#": "G", "Ab": "A", "B": "Bb", "C": "Cb"},
            "Locrian": {"Eb": "Ebb", "F": "Fb", "G#": "G", "A": "Ab", "B": "Bb", "C": "Cb"},
        },
        "D":{
            "Ionian": {"Eb": "E", "F": "F#", "G#": "G", "Ab": "A", "Bb": "B", "C": "C#"},
            "Dorian": {"Eb": "E", "F#": "F", "G#": "G", "Ab": "A", "Bb": "B", "C#": "C"},
            "Phrygian": {"E": "Eb", "F#": "F", "G#": "G", "Ab": "A", "B": "Bb", "C#": "C"},
            "Lydian": {"Eb": "E", "F": "F#", "G": "G#", "Ab": "A", "Bb": "B", "C": "C#"},
            "Mixolydian": {"Eb": "E", "F": "F#", "G#": "G", "Ab": "A", "Bb": "B", "C#": "C"},
            "Aeolian": {"Eb": "E", "F#": "F", "G#": "G", "Ab": "A", "B": "Bb", "C#": "C"},
            "Locrian": {"E": "Eb", "F#": "F", "G#": "G", "A": "Ab", "B": "Bb", "C#": "C"},
        },
        "D#":{
            "Ionian": {"E": "E#", "F#": "F##", "G##": "G#", "A": "A#", "B": "B#", "C#": "C##"},
            "Dorian": {"E": "E#", "F##": "F#", "G##": "G#", "A": "A#", "B": "B#", "C##": "C#"},
            "Phrygian": {"E#": "E", "F##": "F#", "G##": "G#", "A": "A#", "B#": "B", "C##": "C#"},
            "Lydian": {"E": "E#", "F#": "F##", "G#": "G##", "A": "A#", "B": "B#", "C#": "C##"},
            "Mixolydian": {"E": "E#", "F#": "F##", "G##": "G#", "A": "A#", "B": "B#", "C##": "C#"},
            "Aeolian": {"E": "E#", "F##": "F#", "G##": "G#", "A": "A#", "B#": "B", "C##": "C#"},
            "Locrian": {"E#": "E", "F##": "F#", "G##": "G#", "A#": "A", "B#": "B", "C##": "C#"},
        },
        "Eb": {
            "Ionian": {"E": "Eb", "F": "Fb", "G": "Gb", "Abb": "Ab", "Bbb": "Bb", "Cb": "C"},
            "Dorian": {},
            "Phrygian": {},
            "Lydian": {},
            "Mixolydian": {},
            "Aeolian": {},
            "Locrian": {},
        },
        "E": {
            "Ionian": {"F": "F#", "G": "G#", "A#": "A", "Bb": "B", "C": "C#", "D": "D#"},
            "Dorian": {"F": "F#", "G#": "G", "A#": "A", "Bb": "B", "C": "C#", "D#": "D"},
            "Phrygian": {"F#": "F", "G#": "G", "A#": "A", "Bb": "B", "C#": "C", "D#": "D"},
            "Lydian": {"F": "F#", "G": "G#", "A": "A#", "Bb": "B", "C": "C#", "D": "D#"},
            "Mixolydian": {"F": "F#", "G": "G#", "A#": "A", "Bb": "B", "C": "C#", "D#": "D"},
            "Aeolian": {"F": "F#", "G#": "G", "A#": "A", "Bb": "B", "C#": "C", "D#": "D"},
            "Locrian": {"F#": "F", "G#": "G", "A#": "A", "B": "Bb", "C#": "C", "D#": "D"},
        },
        "F": {
            "Ionian": {"Gb": "G", "Ab": "A", "B": "Bb", "Cb": "C", "Db": "D", "Eb": "E"},
            "Dorian": {"Gb": "G", "A": "Ab", "B": "Bb", "Cb": "C", "Db": "D", "E": "Eb"},
            "Phrygian": {"G": "Gb", "A": "Ab", "B": "Bb", "Cb": "C", "D": "Db", "E": "Eb"},
            "Lydian": {"Gb": "G", "Ab": "A", "Bb": "B", "Cb": "C", "Db": "D", "Eb": "E"},
            "Mixolydian": {"Gb": "G", "Ab": "A", "B": "Bb", "Cb": "C", "Db": "D", "E": "Eb"},
            "Aeolian": {"Gb": "G", "A": "Ab", "B": "Bb", "Cb": "C", "D": "Db", "E": "Eb"},
            "Locrian": {"G": "Gb", "A": "Ab", "B": "Bb", "C": "Cb", "D": "Db", "E": "Eb"},
        },
        "F#": {
            "Ionian": {"E": "Eb", "F": "Fb", "G": "Gb", "Abb": "Ab", "Bbb": "Bb", "Cb": "C"},
            "Dorian": {},
            "Phrygian": {},
            "Lydian": {},
            "Mixolydian": {},
            "Aeolian": {},
            "Locrian": {},
        },
        "Gb": {
            "Ionian": {"E": "Eb", "F": "Fb", "G": "Gb", "Abb": "Ab", "Bbb": "Bb", "Cb": "C"},
            "Dorian": {},
            "Phrygian": {},
            "Lydian": {},
            "Mixolydian": {},
            "Aeolian": {},
            "Locrian": {},
        },
        "G": {
            "Ionian": {"Ab": "A","Bb": "B","C#": "C","Db": "D","Eb": "E","F": "F#"},
            "Dorian": {"Ab": "A","B": "Bb","C#": "C","Db": "D","Eb": "E","F#": "F"},
            "Phrygian": {"A": "Ab","B": "Bb","C#": "C","Db": "D","E": "Eb","F#": "F"},
            "Lydian": {"Ab": "A","Bb": "B","C": "C#","Db": "D","Eb": "E","F": "F#"},
            "Mixolydian": {"Ab": "A","Bb": "B","C#": "C","Db": "D","Eb": "E","F#": "F"},
            "Aeolian": {"Ab": "A","B": "Bb","C#": "C","Db": "D","E": "Eb","F#": "F"},
            "Locrian": {"A": "Ab","B": "Bb","C#": "C","D": "Db","E": "Eb","F#": "F"},
        },
        "G#": {
            "Ionian": {"E": "Eb", "F": "Fb", "G": "Gb", "Abb": "Ab", "Bbb": "Bb", "Cb": "C"},
            "Dorian": {},
            "Phrygian": {},
            "Lydian": {},
            "Mixolydian": {},
            "Aeolian": {},
            "Locrian": {},
        },
        "Ab": {
            "Ionian": {"Bbb": "Bb", "Cb": "C", "D": "Db", "Ebb": "Eb", "Fb": "F", "Gb": "G"},
            "Dorian": {"Bbb": "Bb", "C": "Cb", "D": "Db", "Ebb": "Eb", "Fb": "F", "G": "Gb"},
            "Phrygian": {"Bb": "Bbb", "C": "Cb", "D": "Db", "Ebb": "Eb", "F": "Fb", "G": "Gb"},
            "Lydian": {"Bbb": "Bb", "Cb": "C", "Db": "D", "Ebb": "Eb", "Fb": "F", "Gb": "G"},
            "Mixolydian": {"Bbb": "Bb", "Cb": "C", "Db": "D", "Ebb": "Eb", "Fb": "F", "G": "Gb"},
            "Aeolian": {"Bbb": "Bb", "C": "Cb", "Db": "D", "Ebb": "Eb", "F": "Fb", "G": "Gb"},
            "Locrian": {"Bb": "Bbb", "C": "Cb", "Db": "D", "Eb": "Ebb", "F": "Fb", "G": "Gb"},
        },
        "A": {
            "Ionian": {"Bb": "B", "C": "C#", "D#": "D", "Eb": "E", "F": "F#", "G": "G#"},
            "Dorian": {"Bb": "B", "C#": "C", "D#": "D", "Eb": "E", "F": "F#", "G#": "G"},
            "Phrygian": {"B": "Bb", "C#": "C", "D#": "D", "Eb": "E", "F#": "F", "G#": "G"},
            "Lydian": {"Bb": "B", "C": "C#", "D": "D#", "Eb": "E", "F": "F#", "G": "G#"},
            "Mixolydian": {"Bb": "B", "C": "C#", "D#": "D", "Eb": "E", "F": "F#", "G#": "G"},
            "Aeolian": {"Bb": "B", "C#": "C", "D#": "D", "Eb": "E", "F#": "F", "G#": "G"},
            "Locrian": {"B": "Bb", "C#": "C", "D#": "D", "E": "Eb", "F#": "F", "G#": "G"},
        },
        "A#": {
            "Ionian": {"E": "Eb", "F": "Fb", "G": "Gb", "Abb": "Ab", "Bbb": "Bb", "Cb": "C"},
            "Dorian": {},
            "Phrygian": {},
            "Lydian": {},
            "Mixolydian": {},
            "Aeolian": {},
            "Locrian": {},
        },
        "Bb": {
            "Ionian": {"Cb": "C", "Db": "D", "E#": "E", "Fb": "F", "Gb": "G", "Ab": "A"},
            "Dorian": {"Cb": "C", "D": "Db", "E#": "E", "Fb": "F", "Gb": "G", "A": "Ab"},
            "Phrygian": {"C": "Cb", "D": "Db", "E#": "E", "Fb": "F", "G": "Gb", "A": "Ab"},
            "Lydian": {"Cb": "C", "Db": "D", "E": "E#", "Fb": "F", "Gb": "G", "Ab": "A"},
            "Mixolydian": {"Cb": "C", "Db": "D", "E#": "E", "Fb": "F", "Gb": "G", "A": "Ab"},
            "Aeolian": {"Cb": "C", "D": "Db", "E#": "E", "Fb": "F", "G": "Gb", "A": "Ab"},
            "Locrian": {"C": "Cb", "D": "Db", "E#": "E", "F": "Fb", "G": "Gb", "A": "Ab"},
        },
        "B": {
            "Ionian": {"C": "C#", "D": "D#", "E#": "E", "F": "F#", "G": "G#", "A": "A#"},
            "Dorian": {"C": "C#", "D": "D#", "E": "E#", "F": "F#", "G": "G#", "A#": "A"},
            "Phrygian": {"C#": "C", "D#": "D", "E#": "E", "F": "F#", "G#": "G", "A": "A#"},
            "Lydian": {"C": "C#", "D": "D#", "E#": "E", "F": "F#", "G": "G#", "A": "A#"},
            "Mixolydian": {"C": "C#", "D": "D#", "E#": "E", "F": "F#", "G": "G#", "A": "A#"},
            "Aeolian": {"C": "C#", "D": "D#", "E#": "E", "F": "F#", "G": "G#", "A": "A#"},
            "Locrian": {"C": "C#", "D": "D#", "E#": "E", "F": "F#", "G": "G#", "A": "A#"},
        },



    }
